### PR TITLE
Enable slashing db prunning

### PR DESCRIPTION
**Pull request by pablomendezroyo**
Enable slashing db prunning

### CODE REVIEW

**Comment by Pol-Lanski** [comment]
Report:

Something funny has happened. Previously to installing this version:
Screenshot 2022-10-24 at 14 47 58

After installing this version:
Screenshot 2022-10-24 at 15 38 55

The size of the DB has increased!!

Here are the logs of the DB:


```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-10-24 13:36:09.616 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-10-24 13:36:09.616 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-10-24 13:36:09.616 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-10-24 13:36:09.623 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-10-24 13:36:09.634 UTC [13] LOG:  database system was shut down at 2022-10-24 13:35:58 UTC
2022-10-24 13:36:09.641 UTC [1] LOG:  database system is ready to accept connections
2022-10-24 13:36:24.282 UTC [14] LOG:  checkpoints are occurring too frequently (15 seconds apart)
2022-10-24 13:36:24.282 UTC [14] HINT:  Consider increasing the configuration parameter "max_wal_size".
2022-10-24 13:36:31.418 UTC [14] LOG:  checkpoints are occurring too frequently (7 seconds apart)
2022-10-24 13:36:31.418 UTC [14] HINT:  Consider increasing the configuration parameter "max_wal_size".
2022-10-24 13:36:39.238 UTC [14] LOG:  checkpoints are occurring too frequently (8 seconds apart)
2022-10-24 13:36:39.238 UTC [14] HINT:  Consider increasing the configuration parameter "max_wal_size".
2022-10-24 13:36:46.646 UTC [14] LOG:  checkpoints are occurring too frequently (7 seconds apart)
2022-10-24 13:36:46.646 UTC [14] HINT:  Consider increasing the configuration parameter "max_wal_size".
2022-10-24 13:37:07.261 UTC [14] LOG:  checkpoints are occurring too frequently (21 seconds apart)
2022-10-24 13:37:07.261 UTC [14] HINT:  Consider increasing the configuration parameter "max_wal_size".
```

**Comment by Pol-Lanski** [comment]
Update: Size has grown even more in the span of 10 minutes:
Screenshot 2022-10-24 at 15 45 41

**Comment by Pol-Lanski** [comment]
After reverting back to the previous version, the size has not decreased, but the logs of the database do not include the warning of checkpoints occurring too frequently:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-10-24 13:50:32.032 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-10-24 13:50:32.032 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-10-24 13:50:32.032 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-10-24 13:50:32.040 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-10-24 13:50:32.050 UTC [14] LOG:  database system was shut down at 2022-10-24 13:50:20 UTC
2022-10-24 13:50:32.056 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by pablomendezroyo** [comment]
We must look for the optimistic slashing prune parameters

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/pull/42

**Pull request closed without merging**
